on: [push]

name: build-test-release

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-18.04
            artifact_name: libmatrix.so
            asset_name: libmatrix.so-ubuntu-18.04
        rust:
          - stable
      fail-fast: false

    steps:
      - name: Install latest-stable weechat for Ubuntu 18.04
        run: |
          sudo apt update
          sudo apt install dirmngr gpg-agent apt-transport-https
          sudo apt-key adv --keyserver hkps://keys.openpgp.org --recv-keys 11E9DE8848F2B65222AA75B8D1820DB22A11534E
          echo "deb https://weechat.org/ubuntu bionic main" | sudo tee /etc/apt/sources.list.d/weechat.list
          echo "deb-src https://weechat.org/ubuntu bionic main" | sudo tee -a /etc/apt/sources.list.d/weechat.list
          sudo apt update
          sudo apt install weechat-curses weechat-plugins weechat-python weechat-perl weechat-dev
          echo "version of weechat-plugin.h that weechat-sys uses by default:"
          grep -m 1 -n -H "WEECHAT_PLUGIN_API_VERSION" "/usr/include/weechat/weechat-plugin.h"

      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Run cargo build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release

      - name: Run cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --release

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/release/${{ matrix.artifact_name }}
          asset_name: ${{ matrix.asset_name }}
          tag: ${{ github.ref }}
          overwrite: true
          body: "Unstable build. Rename it to `matrix.so` and put it in $WEECHAT_HOME/plugins"
